#cloud-config

# yaml-language-server: $schema=../../schema.json
users:
  - name: tbrasser
    shell: /bin/bash
    groups: [admin]
    ssh_authorized_keys: [github:tbrasser]
install:
  auto: true
  no-format: true
  reboot: true
  grub_options:
    extra_cmdline: >-
      pcie_aspm=off
      nvme_core.default_ps_max_latency_us=0
      gfxpayload=800x600x32
      gfxmode=800x600x32
  extra-dirs-rootfs: &extradirs [/var/lib/longhorn]
p2p:
 disable_dht: true
 auto:
   enable: true
upgrade:
  extra-dirs-rootfs: *extradirs
reset:
  extra-dirs-rootfs: *extradirs
kubevip: { enabled: false }
bundles:
  - targets: [run://quay.io/kairos/community-bundles:flux_latest]
k3s:
  enabled: true
  args:
    - --disable traefik,servicelb
    - --flannel-backend none
    - --disable-network-policy
    - --cluster-cidr=172.23.0.0/18
    - --service-cidr 172.23.64.0/18
    - --write-kubeconfig-mode 0644
    # - --node-label "graphics=dri"
    # - --node-label "node.longhorn.io/create-default-disk=true"
    # - --node-label "longhorn=primary"
    - --kubelet-arg=config=/etc/rancher/k3s/kubelet-config.yaml
flux:
  git:
    url: url=ssh://git@github.com/tbrasser/home-platform.git
    path: manifests
    components-extra: image-reflector-controller,image-automation-controller
    network-policy: "false"
stages:
  kairos-install.pre.before:
    - if: "[ -e /dev/sda ]"
      name: "Conditionally partition sda"
      commands:
        - |
          parted --script --machine -- /dev/sda mklabel gpt
      layout: &layout
        device:
          path: /dev/sda
        expand_partition:
          size: 0 # All available space
        add_partitions:
          # -- All sizes bellow are in MB
          - fsLabel: COS_OEM
            size: 64
            pLabel: oem
          # -- https://github.com/kairos-io/kairos/issues/1265#issuecomment-1621433780
          - fsLabel: COS_ACTIVE
            size: &os-size 8500
            pLabel: system
          - fsLabel: COS_RECOVERY
            size: *os-size
            pLabel: recovery
          - fsLabel: COS_STATE
            size: 18000
            pLabel: state
          - fsLabel: COS_PERSISTENT
            pLabel: persistent
            size: 25000
            filesystem: "ext4"
    - if: "[ ! -e /dev/sda ]"
      name: "Conditionally partition nvme0n1"
      commands:
        - |
          parted --script --machine -- /dev/nvme0n1 mklabel gpt
      layout:
        <<: *layout
        device:
          path: /dev/nvme0n1

  after-install-chroot:
    # -- These are in this repo
    - name: "Add cluster-specific manifests from GitHub"
      downloads:
        - url: https://raw.githubusercontent.com/tbrasser/home-platform/main/manifests/tigera-operator.yaml
          path: /var/lib/rancher/k3s/server/manifests/tigera-operator.yaml
        - url: https://raw.githubusercontent.com/tbrasser/home-platform/main/manifests/calico-crds.yaml
          path: /var/lib/rancher/k3s/server/manifests/calico-crds.yaml
        - url: https://raw.githubusercontent.com/tbrasser/home-platform/main/manifests/flux-system-namespace.yaml
          path: /var/lib/rancher/k3s/server/manifests/flux-system-namespace.yaml
        - url: https://raw.githubusercontent.com/tbrasser/home-platform/main/manifests/kubelet-config.yaml
          path: /etc/rancher/k3s/kubelet-config.yaml

  # -- https://github.com/derailed/k9s/issues/1399
  initramfs:
    - name: Increase number of open files
      sysctl:
        fs.inotify.max_user_instances: "8192"
        fs.inotify.max_user_watches: "524288"

  boot:
    - name: "Format /dev/nvme0n1 if unformatted and Kairos is installed to /dev/sdX"
      # -- Double brackets needed for regex compare
      if: >-
        [[ $(lsblk -o NAME,LABEL | grep OEM) =~ "-sd" ]] &&
        [[ ! $(fdisk -lo type /dev/nvme0n1 | tail -n 1) =~ "Linux" ]]
      commands:
        - parted /dev/nvme0n1 --script -a optimal -- mklabel gpt mkpart longhorn ext4 0% 100%
        - &partition mkfs.ext4 -F /dev/nvme0n1p1

    - name: "Partition /dev/nvme0n1p1 if unpartitioned and Kairos is installed to /dev/sdX"
      if: >-
        [[ $(lsblk -o NAME,LABEL | grep OEM) =~ "-sd" ]] &&
        [[ $(lsblk -no FSTYPE /dev/nvme0n1p1) != "ext4" ]]
      commands:
        - *partition

    - name: "Mount /dev/nvme0n1p1 under /var/lib/longhorn if it exists and Kairos is installed to /dev/sdX"
      if: >-
        [[ $(lsblk -o NAME,LABEL | grep OEM) =~ "-sd" ]] &&
        [[ $(lsblk -no FSTYPE /dev/nvme0n1p1) == "ext4" ]]
      commands:
        # -- https://github.com/kairos-io/packages/blob/3482fed51f21a2155b60a0aa9ac91b1d839d1029/packages/static/kairos-overlay-files/files/system/oem/00_rootfs_uki.yaml#L43
        - umount /var/lib/longhorn
        - mount -o rw /dev/nvme0n1p1 /var/lib/longhorn

    - name: "Set up various kube environment variables"
      environment:
        KUBECONFIG: /etc/rancher/k3s/k3s.yaml
        CONTAINERD_ADDRESS: /run/k3s/containerd/containerd.sock
        CONTAINERD_NAMESPACE: k8s.io
