state_dir: "/storage"
artifact_version: v2.4.1-k3sv1.27.3+k3s1
release_version: v2.4.1
# artifact_version: v2.4.0-k3sv1.26.6+k3s1
# release_version: v2.4.0
flavor: debian
repository: kairos-io/kairos
# # -- This adds files to AuroraBoot to serve them but the arguments
# # are also passed at boot-time, screwing up the boot
# netboot:
#   cmdline: >-
#     rd.live.overlay.overlayfs
#     rd.neednet=1
#     ip=dhcp
#     rd.cos.disable
#     netboot
#     nodepair.enable
#     console=tty1
#     console=ttyS0
#     console=tty0
#     custom_config={{ ID "/storage/config_extra.yaml" }}
#     sops_secret={{ ID "/storage/sops_secret.yaml" }}
