#cloud-config

users:
  - name: tyzbit
    shell: /bin/bash
    groups:
      - admin
    ssh_authorized_keys:
      - github:tyzbit

install:
  auto: true
  device: /dev/sda
  reboot: true
  extra-dirs-rootfs: &longhorn
    - /mnt/longhorn
  bundles:
    - rootfs_path: /usr/local/lib/extensions/flux
      targets:
        # # If this is merged, use the commented out line instead
        # # https://github.com/kairos-io/community-bundles/pull/53
        # - container://quay.io/kairos/community-bundles:flux_latest
        - container://docker.io/tyzbit/flux:latest

upgrade:
  extra-dirs-rootfs: *longhorn

reset:
  extra-dirs-rootfs: *longhorn

growpart:
  devices: ["/"]

kubevip:
  enabled: false
  # eip: 192.168.1.8

stages:
  # Runs once
  after-install-chroot:
    - name: "Increase display console text size"
      commands:
        - sed -i 's/8x16/16x32/g' /etc/default/console-setup

    - name: "Disable onboard network"
      files:
        - path: /etc/systemd/network/10-disable-onboard.network
          permissions: 0644
          content: |
            [Match]
            Name=enp0*
            [Link]
            Unmanaged=true

    # TODO: https://kairos.io/docs/reference/build-from-scratch/
    - name: "Configure to use m.2 Realtek card"
      files:
        - path: /etc/modprobe.d/blacklist-r8169.conf
          permissions: 0644
          content: |
            blacklist r8169
        - path: /etc/apt/sources.list.d/debian-nonfree.list
          permissions: 0644
          content: |
            deb http://ftp.us.debian.org/debian trixie main non-free-firmware

    - name: "Install Realtek firmware"
      commands:
        - apt-get update
        - apt-get install -y firmware-realtek
        - apt-get clean && rm -rf /var/lib/apt/lists/*
        # - rmmod r8169
        # - modprobe r8125
        - update-initramfs -u

    # # -- The pre config has the p2p.network_token
    # # -- (only `commands`,`entities` and `files` may have templating)
    - name: "Download additional pre-config"
      downloads:
        - url: http://nas.onair/sensitive_configs.yaml
          path: /oem/50_sensitive_configs.yaml

    - name: "Configure as control plane or worker"
      files:
        - path: /oem/60_k3s_config.yaml
          content: |
            #cloud-config
            {{- $control := false -}}
            {{- $first := false -}}
            {{- range $net := .Values.network -}}
              {{- range $mac := list "48:4d:7e:e7:6a:27" "8c:ae:4c:dd:1f:5b" "8c:ae:4c:dd:18:7a" "8c:ae:4c:dd:18:54" -}}
                {{- if eq $net.macaddress $mac -}}
                    {{- $control = true -}}
                {{- end -}}
              {{- end -}}
              {{- if eq $net.macaddress "48:4d:7e:e7:6a:27" -}}
                  {{- $first = true -}}
              {{- end -}}
            {{- end -}}
            {{- $id := randAlphaNum 5 | lower -}}
            {{- if $control }}
            hostname: neuron-{{ $id }}
            k3s:
              enabled: true
              args:
            {{- if $first }}
                - --cluster-init
            {{- end }}
                - --disable traefik,servicelb
                - --flannel-backend none
                - --disable-network-policy
                - --service-cidr 172.23.64.0/18
                - --write-kubeconfig-mode 0644
                - --node-taint node-role.kubernetes.io/control-plane=effect:NoSchedule
            {{- else }}
            hostname: myocite-{{ $id }}
            k3s-agent:
              enabled: true
              args:
                - --node-label "node.longhorn.io/create-default-disk=true"
            {{- end }}

    # -- This is needed now so we can add the SOPS secret
    - name: "Add flux-system namespace manifest"
      files:
        - path: /var/lib/rancher/k3s/server/manifests/flux-system.yaml
          content: |
            apiVersion: v1
            kind: Namespace
            metadata:
              name: flux-system

    - name: "Install Calico"
      downloads:
        - url: https://raw.githubusercontent.com/projectcalico/calico/v3.26.1/manifests/tigera-operator.yaml
          path: /var/lib/rancher/k3s/server/manifests/calico-operator.yaml
        - url: https://raw.githubusercontent.com/tyzbit/kairos-config/main/k3s/manifests/calico-crds.yaml
          path: /var/lib/rancher/k3s/server/manifests/calico-crds.yaml
    - name: "Add CalicoNodeStatus resource"
      files:
        - path: /var/lib/rancher/k3s/server/manifests/calico-node-status.yaml
          content: |
            apiVersion: crd.projectcalico.org/v1
            kind: CalicoNodeStatus
            metadata:
              name: {{ .Values.node.hostname }}
            spec:
              classes:
                - Agent
                - BGP
                - Routes
              node: {{ .Values.node.hostname }}
              updatePeriodSeconds: 10

    - name: "Download SOPS secret"
      downloads:
        - url: http://nas.onair/sops_secret.yaml
          path: /var/lib/rancher/k3s/server/manifests/sops-secret.yaml

  # Runs once
  initramfs:
    - name: "Partition /dev/nvme0n1 if needed"
      if: >-
        [ $(fdisk -l /dev/nvme0n1 | grep -q "83 Linux"; echo $?) -ne 0 ]
      commands:
        - parted /dev/nvme0n1 --script -a optimal -- mklabel gpt mkpart longhorn ext4 0% 100%

    - name: "Format /dev/nvme0n1p1 if needed"
      if: >-
        [ $(lsblk -o FSTYPE /dev/nvme0n1p1 | grep -v -E '^$|FSTYPE' | wc -l) -eq 0 ]
      commands:
        - mkfs.ext4 -F /dev/nvme0n1p1

  boot:
    - name: "Restart console"
      commands:
        - service console-setup restart

    - name: "Mount /dev/nvme0n1p1 under /mnt/longhorn"
      commands:
        - mount -o rw /dev/nvme0n1p1 /mnt/longhorn

    - name: "Set up various kube environment variables"
      environment:
        KUBECONFIG: /etc/rancher/k3s/k3s.yaml
        CONTAINERD_ADDRESS: /run/k3s/containerd/containerd.sock
        CONTAINERD_NAMESPACE: k8s.io

    - name: "Bootstrap with Flux"
      commands:
        - bash /usr/local/lib/extensions/flux/bootstrap.sh &

# # p2p is commented out because while I'd love to use it,
# # I want to be weird and set different hostnames for control plane nodes
# # and workers, and that requires me to template the k3s configuration
# # like I do above
# # See https://github.com/kairos-io/kairos/issues/1877
# p2p:
#   network_id: spartacus
#   network_token: [[.p2p.network_token]]
#   dns: false
#   # disable_dht: true
#   auto:
#     enable: true
#     ha:
#       enable: true
#       # -- ADDITIONAL control plane nodes
#       # master_nodes: 1
#   vpn:
#     create: false
#     enable: false
#     # env:
#       # DNSFORWARD: "true"
#       # DNSCACHESIZE: "200"
#       # DNSFORWARDSERVER: "192.168.1.1:53"

# -- Bundle configs
# -- Flux
flux:
  github:
    owner: tyzbit
    repository: fleet-infra
    path: clusters/spartacus # FIXME
    components-extra: image-reflector-controller,image-automation-controller
