listen_addr: :8081
state_dir: "/storage"
# artifact_version: v2.4.1-k3sv1.27.3+k3s1
# release_version: v2.4.1
# flavor: debian
# repository: kairos-io/kairos
# container_image: quay.io/kairos/kairos-debian:v2.4.1-k3sv1.27.3-k3s1
container_image: ghcr.io/tyzbit/kairos-distros:debian-v3.0.10-k3sv1.29.3-k3s1-53
